
name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate blue-purple contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: sheikhsiddique722-sketch
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%237C3AED&color_dots=%230B1220,%231E3A8A,%232563EB,%2360A5FA,%23C4B5FD
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23A78BFA&color_dots=%230B1220,%231E1B4B,%233B2F80,%236D5AE6,%23C4B5FD

      - name: Publish animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
